added bbox filtering to 'tilekiln-generate area'
pnorman/tilekiln-old pull request #18
Opened 2021-06-07 19:34 UTC by ttomasz

issue #8 

adds --bbox parameter to 'tilekiln-generate area' utility which allows restricting generated tiles to smaller area
bbox is provided as a string with coordinates separated by commas e.g.: -180,-90,180,90 for the entire world (which is the default if no value provided)

2021-06-07 19:35 UTC, ttomasz commented
@pnorman please let me know if this is ok or if fixes are required

2021-06-16 19:40 UTC, ttomasz commented
@pnorman have you had the chance to review this PR?

2021-06-17 01:40 UTC, pnorman requested changes
Looks good, but it's failing CI because some of the new lines are too long for flake8

2021-06-17 19:46 UTC, ttomasz commented
i changed to fit 80 char line limit (which is pretty low imo :)

2021-06-18 07:52 UTC, merged